### ISSUE TITLE
Escaped backslashes

### ISSUE THREAD

**Issue by eush77** [featurist/shellsubstitute#2]
Hello!

This module does not currently support escaped backslashes:

``` js
> substitute('\\\\${USER}', { USER: 'Josh' })
'\\${USER}'
```

Expected: `'\\\\Josh'` or `'\\Josh'`.

This is easy to implement (see [this code from npm](https://github.com/npm/npm/blob/580f88a8183375a9c045529f10bf1aaea75f7bdd/lib%2Fconfig%2Fcore.js#L408-L422) for example) but I need to know a resolution on whether backslashes are interpreted or preserved (#1) first.

**Comment by refractalize** [comment]
this is fixed in 099f40a1973d2698be840e457b8f8dd618ca7e88.

`\$USER` => `$USER`
`\\$USER` => `\Josh`
`\\\$USER` => `\$USER`
`\\\\$USER` => `\\Josh`
`\\\\\$USER` => `\\$USER`

etc.

**Comment by refractalize** [comment]
in v1.20
